name: 'gabrielbb/xvfb'
description: 'Install xvfb and run commands with it'
inputs:
  run:
    description: 'Command to execute using xvfb'
    required: true
runs:
  using: 'node12'
  main: 'index.js'