on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Test XVFB
        uses: ./
        with:
          run: echo 'Testing xvfb'

      - name: Test XVFB with working directory
        uses: ./
        with:
          working-directory: ./node_modules
          run: echo 'Testing xvfb in custom directory'